Refactor
radars-app/radar-chart pull request #22
Opened 2020-11-11 09:26 UTC by vladimir-sviridenko

2020-11-11 10:36 UTC, clain-atomi requested changes

2020-11-11 10:36 UTC, clain-atomi commented on src/libs/dividers/dividers.renderer.ts
> +	private calculateRange(rangeX: number, rangeY: number, config: RadarChartConfig): number {
please create more meaningful name, like `calculateRingRadius` or `calculateRangeBetweenEachRing` or `calculateRingWidth`, each method must have name that represents what this method do.

2020-11-11 10:36 UTC, clain-atomi commented on src/libs/dividers/dividers.renderer.ts
> +			const range: number = this.calculateRange(rangeX, rangeY, config);
add more maningfull name like `ringWidth`

2020-11-11 10:36 UTC, clain-atomi commented on src/libs/dividers/dividers.renderer.ts
> +	private calculateDividers(sectorNames: string[]): Divider[] {
createDividerModels

2020-11-11 10:36 UTC, clain-atomi commented on src/libs/dividers/dividers.renderer.ts
>  		const startRotation: number = 270;
add `degree` postfix to variables you use.

2020-11-11 10:36 UTC, clain-atomi commented on src/libs/dividers/dividers.renderer.ts
> +	private markLabeledDivider(dividers: Divider[]): void {
setLabeledDivider

2020-11-11 10:36 UTC, clain-atomi commented on src/libs/dividers/dividers.renderer.ts
> +			.attr('x1', 0).attr('y1', 0)
move .attr calls to new line each

2020-11-11 10:36 UTC, clain-atomi commented on src/libs/dividers/labels/labels.renderer.ts
> +	public render(backgroundContainer: D3Selection, textContainer: D3Selection, range: number, ringNames: string[]): void {
please work with class names to make them BEM like.
g.divider
=> line.divider__line
=> g.divider__labels
=> => text.label
=> g.divider__labels-background
=> => rext.label-backgound

2020-11-11 10:36 UTC, clain-atomi commented on src/libs/helpers/convert-to-class-name.ts
>  	return name.replace(/\s/g, '').toLowerCase();
looks like this method is just `String.trim` method

2020-11-11 10:36 UTC, clain-atomi commented on src/libs/radar-chart/radar-chart.renderer.ts
>  		private svg: D3Selection,
svgElement

2020-11-11 10:36 UTC, clain-atomi commented on src/libs/radar-chart/radar-chart.renderer.ts
>  		private svg: D3Selection,
also i think better get raw svg html element and then inside our renerer wrap it with d3.select(), this way we can avoid adding d3.js dependency to our consumers.

2020-11-11 10:36 UTC, clain-atomi commented on src/libs/radar-chart/radar-chart.renderer.ts
> +			new BehaviorSubject(this.config)
just pass `config$`

2020-11-11 10:36 UTC, clain-atomi commented on src/libs/radar-chart/radar-chart.renderer.ts
> +			new BehaviorSubject(this.config)
just pass `config$`

2020-11-11 10:36 UTC, clain-atomi commented on src/libs/radar-chart/radar-chart.renderer.ts
>  			this.dividersRenderer.config$.next(config);
can be removed

2020-11-11 10:36 UTC, clain-atomi commented on src/libs/rings/rings.renderer.ts
> +		combineLatest([this.model.rangeX$, this.model.rangeY$, this.config$, this.model.ringNames$])
improve formatting here

2020-11-11 10:36 UTC, clain-atomi commented on src/radar-demo.ts
>  import { RadarChartConfig } from './libs/radar-chart/radar-chart.config';
please exclude src/radar-demo.ts from repository, it should be your local thing.

2020-11-12 10:54 UTC, vladimir-sviridenko commented on package.json
> -		"d3-zoom": "^2.0.0",
d3 includes d3-zoom. checked

2020-11-13 09:54 UTC, vladimir-sviridenko commented on src/libs/dividers/dividers.renderer.ts
> +		public readonly config$: BehaviorSubject<RadarChartConfig>
That is to prevent rewriting of config. If user wants to change config he can only call next in existing config$. If he changes config$ to the new Subject he can forget to call next method. So, we have not updated chart.

2020-11-13 12:08 UTC, clain-atomi requested changes

2020-11-13 12:08 UTC, clain-atomi commented on src/libs/dividers/labels/labels.renderer.ts
> +	private get config(): RadarChartConfig {
remove this or use it inside labelsConfig()

2020-11-13 13:00 UTC, merged